<?php

define( 'DIEFINNHUTTE_CORE_VERSION', '1.2.1' );
define( 'DIEFINNHUTTE_CORE_ABS_PATH', dirname( __FILE__ ) );
define( 'DIEFINNHUTTE_CORE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'DIEFINNHUTTE_CORE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'DIEFINNHUTTE_CORE_ASSETS_PATH', DIEFINNHUTTE_CORE_ABS_PATH . '/assets' );
define( 'DIEFINNHUTTE_CORE_ASSETS_URL_PATH', DIEFINNHUTTE_CORE_URL_PATH . 'assets' );
define( 'DIEFINNHUTTE_CORE_CPT_PATH', DIEFINNHUTTE_CORE_ABS_PATH . '/post-types' );
define( 'DIEFINNHUTTE_CORE_CPT_URL_PATH', DIEFINNHUTTE_CORE_URL_PATH . 'post-types' );
define( 'DIEFINNHUTTE_CORE_SHORTCODES_PATH', DIEFINNHUTTE_CORE_ABS_PATH . '/shortcodes' );
define( 'DIEFINNHUTTE_CORE_SHORTCODES_URL_PATH', DIEFINNHUTTE_CORE_URL_PATH . 'shortcodes' );

define( 'DIEFINNHUTTE_CORE_OPTIONS_NAME', 'qodef_options_diefinnhutte' );